version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - promanage_network

  backend:
    build: ./backend
    command: sh -c "python manage.py makemigrations accounts projects tasks && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=project_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-key
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    networks:
      - promanage_network

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - promanage_network

volumes:
  postgres_data:

networks:
  promanage_network:
    driver: bridge
